Python 3.13.0a4 (tags/v3.13.0a4:9d34f60, Feb 15 2024, 17:00:30) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> ## 2번 문제, 틀린 부분 2곳을 찾아서 맞게 고치세요.
... def __init__(self):
...     self. color=""
...     self.speed=0
... 
...     
>>> def upSpeed(self, value):
...     self.speed += value
... 
...     
>>> ## 4번 문제 , 속도를  50으로 초기화하는 클래스의 생성자 코드
... class Horse:
...     def __init__(self):
...         self.speed=50
... 
...         
>>> ##6번 클래스의 상속과 관련된 코드 중 실행 결과는?
... ### 답: 3번 슈퍼클래스, 서브 클래스
...         
>>> ## Car의 상속을 받는 RVCar 클래스를 정의하는 코드
... ### 답 : classa RVCar(Car):
...         
